### ISSUE TITLE
Should labels propagate when doing arithmetic?

### ISSUE THREAD

**Issue by rpruim** [dusadrian/declared#1]
Current behavior:

``` r
suppressPackageStartupMessages(library("declared"))
x <- declared(1:10, label =  "one through ten")
y <- (x - mean(x))/sd(x)
y
#> <declared<numeric>[10]> one through ten
#>  [1] -1.4863011 -1.1560120 -0.8257228 -0.4954337 -0.1651446  0.1651446
#>  [7]  0.4954337  0.8257228  1.1560120  1.4863011
```

<sup>Created on 2021-06-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

When performing arithmetic, it is unlikely that the labels will still apply to the result, so perhaps it would be better to remove the labelling.

See tidymodels/broom#1032 and tidymodels/broom#1031 for consequences in {broom}.

**Comment by dusadrian** [comment]
That's true @rpruim, I'll think of a solution, don't even understand how this propagates though.

**Comment by dusadrian** [comment]
@rpruim 
Fixed, in the latest development version:

``` r
library(declared)
x <- declared(1:10, label =  "one through ten")
y <- (x - mean(x))/sd(x)
y
#  [1] -1.4863011 -1.1560120 -0.8257228 -0.4954337 -0.1651446  0.1651446  0.4954337
#  [8]  0.8257228  1.1560120  1.4863011
```

**Comment by rpruim** [comment]
Thanks for the quick action.  I've only done a quick check, but it seems to be doing what I was thinking.

**Comment by dusadrian** [comment]
Hi Randall,

Apparently, forcing to drop the arguments within the \`-\`() function has unexpected and undesired side effects:
```
foo <- function(x) {
    return(substitute(x))
}

foo(1 - x)
1 - x

library(declared)
foo(1 - x)
`-`(1, x)
```

This is not good news for some of my other packages which need substitute() and do not like this side effect.
Looking at https://github.com/tidymodels/broom/pull/1032, the best advice is to simply add code that eliminates the offending attributes.

This is exactly what I did by tampering the base function \`-\`(), but faced with the side effects I will likely remove this functionality. Is this highly problematic for your code?
