### ISSUE TITLE
Coercion to integer

### ISSUE THREAD

**Issue by SarahGoslee-USDA** [dusadrian/declared#2]
This package is nifty, and it's been on my list to try out since the discussion on R-help.

It is almost perfect for my needs, but I'm running into a problem with coercion to integer.

On my real dataset, I get the warning 

Warning message:
In admisc::coerceMode(x) : NAs introduced by coercion to integer range

and indeed, some values are converted to NA.

I tracked the problem to this function (and probably the other mode functions, since changing this one didn't fix my problem):

```

likely_mode <- function(x) {
    if (admisc::possibleNumeric(x) || all(is.na(x))) {
        x <- admisc::asNumeric(x)
        if (admisc::wholeNumeric(x) & !is.integer(x)) {
            x <- as.integer(x)
        }
    }

    return(x)
}
```

which calls admisc::wholeNumeric(x), and there's the problem. Some of my values are whole numbers, but too large for the integer type.

Here's a toy example:

```
x <- c(1, -9998, 2, 3, -9999, 14773403430)
declared(x,
                 labels = c("(D)" = -9999, "(Z)" = -9998),
                 na_values = c(-9999, -9998),
                 label = "Values")

<declared<integer>[6]> Values
[1]         1 NA(-9998)         2         3 NA(-9999)        NA
Missing values: -9999, -9998

Labels:
 value label
 -9999   (D)
 -9998   (Z)
Warning message:
In admisc::coerceMode(x) : NAs introduced by coercion to integer range
```

The help for wholeNumeric() specifically warns against this problem:

     Function *‘wholeNumeric()’* tests if numbers in a vector are whole
     (round) numbers. Whole numbers are different from “integer”
     numbers (which have special memory representation), and
     consequently the function *‘is.integer’()* tests something
     different, how numbers are stored in memory (see the description
     of function *‘double()’* for more details).

As a work-around, I tried adding 0.1 to my first non-missing value, and then subtracting it later, but that doesn't actually work, because the subtraction coerces it back to integer.

```
x <- c(1, -9998, 2, 3, -9999, 14773403430)
x[1] <- x[1] + .1
x <- declared(x,
                 labels = c("(D)" = -9999, "(Z)" = -9998),
                 na_values = c(-9999, -9998),
                 label = "Values")

# good: keeps numeric values
<declared<numeric>[6]> Values
[1] 1.10000e+00   NA(-9998) 2.00000e+00 3.00000e+00   NA(-9999) 1.47734e+10
Missing values: -9999, -9998

Labels:
 value label
 -9999   (D)
 -9998   (Z)


x[1] <- x[1] - .1

> x[1] <- x[1] - .1
Warning message:
In admisc::coerceMode(x) : NAs introduced by coercion to integer range
>
> x
<declared<integer>[6]> Values
[1]         1 NA(-9998)         2         3 NA(-9999)        NA
Missing values: -9999, -9998

Labels:
 value label
 -9999   (D)
 -9998   (Z)

```

**Comment by dusadrian** [comment]
Hi @sgoslee,

Thanks for this, I haven't thought of this possibility until your issue.
Already fixed in package admisc, please install the new version using:
`remotes::install_github("dusadrian/admisc")`

The former function `likely_mode()` is now called `coerceMode()`, and the fix is associated with this particular function.

**Comment by SarahGoslee-USDA** [comment]
Thanks for the remarkably prompt response. The function likely_mode() that is causing me the problem is in declared, though, embedded in the declared.R code file.

**Comment by dusadrian** [comment]
Actually, despite having submitted a new CRAN version 0.8, I neglected to push it here, on GitHub. The function `likely_mode()` was already gone, as per the warning message you got:

```
Warning message:
In admisc::coerceMode(x) : NAs introduced by coercion to integer range
```

So the CRAN version is already using `coerceMode()` from package **admisc**, which is now fixed on GitHub and will make it in the next CRAN release (with thanks).

I've re-tested your example, using the latest CRAN version of package **declared**, plus the latest GitHub development version of package **admisc**, and it seems to work as intended:

```
install.packages("declared")
remotes::install_github("dusadrian/admisc", ref = "60b7139")

library(declared)
x <- c(1, -9998, 2, 3, -9999, 14773403430)
declared(x,
    labels = c("(D)" = -9999, "(Z)" = -9998),
    na_values = c(-9999, -9998),
    label = "Values")

<declared<numeric>[6]> Values
[1]           1   NA(-9998)           2           3   NA(-9999) 14773403430
Missing values: -9999, -9998

Labels:
 value label
 -9999   (D)
 -9998   (Z)
```

**Comment by SarahGoslee-USDA** [comment]
Got it! Installing the latest versions fixes my issue, both on the test example and on my real dataset. Thank you so much!

**Comment by dusadrian** [comment]
You're welcome, Sarah, glad it helps :)
