### ISSUE TITLE
Coercion

### ISSUE THREAD

**Issue by antaldaniel** [dusadrian/declared#3]
I am the author and maintainer of the retroharmonize package which is used for retrospective survey harmonization.  It has solved this problem differently. Nevertheless, I would be happy to use declared to avoid paralell development, and to find synergies with DDIwR, but I think that two important methods should be implemented in declared. 

My class has as_numeric, as_factor, and as_character() methods that are coercing my version of the labelled class  to base R types, which I think is a very critical requirements to work with most statistical libraries. My package relies on rlang and vctrs, and I think that all modern R packages should, because base R has some really ambigous solutions.  For example, having a typed NA value is extremely important to avoid unexpected coercion behavior. 

To take this example
`x  <- declared ( c(1, 2, 3, 4, 5.55, 99), na_values = "99")`
Should have the following expected results:

`as_numeric(x)  #should result in 
1,2,3,4,5.55, NA_real_`

`as_character(x)  #should result in
"1","2","3","4","5.55", NA_character_`

`y <- declared(
  c(1:5, -1),
  labels = c(Good = 1, Bad = 5, DK = -1),
  na_values = -1
)`

currently coercies to an illogical results, in my opinion, because it 
`
which (is.na(as.factor(y)))`

results in 2,3,3, an as_factor methos should instead result in 5, i.e. make DK missing. 

I thinkt that the usability of declared without clear coercion rules to the fundamental R types makes the package very difficult to use in any real life situation.

**Comment by dusadrian** [comment]
Hello @antaldaniel,
(EDITed answer)

I believe this requires a more detailed discussion about the "expected" results, but I just realized the default behavior of `as.character()` is not consistent with the default behavior of `as.numeric()` (for which there is no custom class method), and that is indeed confusing.

I pushed a new development version 0.17.1, with a new argument `drop_na = TRUE` (so activated by default), to leave it optional for the users whether to preserve the declared missing values or not.

```
remotes::install_github("dusadrian/declared", ref = "b6f5507")
> as.factor(y)
[1] Good 2    3    4    Bad  <NA>
Levels: Good 2 3 4 Bad

> as.character(y)
[1] "Good" "2"    "3"    "4"    "Bad"  NA  
```

For those users still wanting to preserve the missing values:

```
> as.factor(y, drop_na = FALSE)
[1] Good 2    3    4    Bad  DK  
Levels: Good 2 3 4 Bad DK

> as.character(y, drop_na = FALSE)
[1] "Good" "2"    "3"    "4"    "Bad"  "DK" 
```

**Comment by antaldaniel** [comment]
@dusadrian I just checekd the new version, and I think that this version is great, and the default value is well-defined.  Most statistical functions will use numerics or factors as inputs, so the declared can be easily put in a pipeline. 
The character representation in my view is used for visualization (for example, ggplot labels), or as an intermediary class for some dirty relabelling or relevelling.

**Comment by dusadrian** [comment]
Great to hear that.
It would have been fantastic to submit this issue a couple of days ago, before pushing the new version to CRAN. This modification will make it to CRAN in one or two months.
