### ISSUE TITLE
NA labels collapse with dplyr::count

### ISSUE THREAD

**Issue by khusmann** [dusadrian/declared#7]
Hello! Was playing around with this and got unexpected behavior with `dplyr::count()` -- It looks like labels collapse into a single NA:

``` r
tibble(x = declared(c(1,2,"a", "b", "a", 1, 2, "b", "b"), na_values=c("a", "b"))) |> count(x)
#> # A tibble: 3 × 2
#>   x             n
#>   <chr+lbl> <int>
#> 1     1         2
#> 2     2         2
#> 3 NA(a)         5
```

I would have expected this:

``` r
#> # A tibble: 3 × 2
#>   x             n
#>   <chr+lbl> <int>
#> 1     1         2
#> 2     2         2
#> 3 NA(a)         2
#> 4 NA(b)         3
```

**Comment by khusmann** [comment]
Looks like the same issue is more generally related to `group_by()`:

```r
tibble(x = declared(c(1,2,"a", "b", "a", 1, 2, "b", "b"), na_values=c("a", "b"))) |> group_by(x) |> summarize(n = n())
#> # A tibble: 3 × 2
#>   x             n
#>   <chr+lbl> <int>
#> 1     1         2
#> 2     2         2
#> 3 NA(a)         5
```

**Comment by dusadrian** [comment]
This issue has the same explanation as the [previous one](https://github.com/dusadrian/declared/issues/8) opened.
In a nutshell, this is not a bug in package **declared**, but a missing feature in tidyverse.
Objects of class "declared" are generic, so other packages can write specific class methods for this type of object. In principle, I could write my own class methods for tidyverse but this is risky for multiple reasons. First, if they change something I'll have to monitor all of their changes and adjust my methods accordingly. But second and most important, tidyverse is just one of the potentially infinite number of possible R extensions. It is extremely possible that other "x"verse or "y"verse will appear in the future, and package **declared** will not be able to monitor the entire R ecosystem to write custom class methods for all possible existing and future packages.
It is their job to write their own class methods for the "declared" objects... should they find it valuable.
I guess this is a chicken and egg problem: if package declared will be extensively used, other packages will comply. But it is their compliance that will extend the usage of package declared.
For the moment, everything works fine with base R, and that should be enough for most users.

**Comment by dusadrian** [comment]
Forgot to mention, this should be an equivalent:
```r
foo <- tibble(x = declared(c(1,2,"a", "b", "a", 1, 2, "b", "b"), na_values=c("a", "b")))
foo$x |> w_table()

  fre    rel   per   vld   cpd
  ----------------------------
1   2  0.222  22.2  50.0  50.0 
2   2  0.222  22.2  50.0 100.0 
-
a   2  0.222  22.2 
b   3  0.333  33.3 
  ----------------------------
    9  1.000 100.0
```

Note that, similarly to SPSS, it separates "valid" from (declared) "missing" values in the frequencies.

**Comment by khusmann** [comment]
> But second and most important, tidyverse is just one of the potentially infinite number of possible R extensions
> It is extremely possible that other "x"verse or "y"verse will appear in the future, and package declared will not be able to monitor the entire R ecosystem
> It is their job to write their own class methods for the "declared" objects... should they find it valuable.

I agree in principle, but I think the tidyverse is a special case and is here to stay. In 2021, [40% of R packages had a tidyverse dependency](https://lrdegeest.github.io/blog/totalverse)... I wouldn't be surprised if that percentage was quite a bit higher now.

I think tidyverse support on this package could really help with adoption, at least in the short term. I know it'd help me sell it to many of my colleagues, at least. And if we can get this idea to catch on in the short term, then any future "x"verse or "y"verse will be compelled to support it as well, without our involvement :)

In the meantime, I think the worrisome aspect of the `group_by()` behavior is that **the result has the appearance of being properly declared, but the label is actually incorrect**. This could give a user the wrong impression that they were getting a correct count of the number of cases missing by that label, when it is in fact not the case. The big selling point of this package is that it fixes a bunch of unexpected behavior that occurs with the commonly used `haven` types, and so this unexpected behavior works directly works against your pitch for this package... even if it is technically a tidyverse-specific issue.

If this is something you're going to wait on the tidyverse coming around to resolve, I think there needs to be front-and-center mention in the documentation somewhere, at least, given it's heavy use in the R ecosystem. Case in point, most of the people I want to immediately recommend this package to are tidyverse users, and this issue has the potential to be an unwelcome surprise if they are not pre-warned...

> I guess this is a chicken and egg problem

I agree. It pains me how the of labeled missingness simply doesn't exist in open source software and formats. The folks designing open software don't seem to see this need, and social scientists don't seem to realize that this is something they can (and should) demand in their software. I'd love to brainstorm with you more about how we can bridge this gap...

> Forgot to mention, this should be an equivalent:

This is good to know, but unfortunately doesn't give me the same kind of flexibility I get with dplyr pipelines. For example, given a data frame with variables `x` and `y`, I could compute the mean value of `y` for each missing value of `x` in addition to their counts like this:

```r
tibble(
  x = declared(c(1,2,"a", "b", "a", 1, 2, "b", "b"), na_values=c("a", "b")),
  y = 1:9,
) |>
  group_by(x) |>
  summarize(y_mean = mean(y), n = n()) |>
  filter(is.na(x))
#> # A tibble: 2 × 3
#>   x         y_mean     n
#>   <chr+lbl>  <dbl> <int>
#> 1 NA(a)        4       2
#> 2 NA(b)        7       3
```

This allows me to very quickly put together queries to answer questions like, "what is the average age of participants who missed this item, for each missing reason?", etc.

**Comment by khusmann** [comment]
Similarly, this common `group_by()` pattern gives unexpected / misleading results:

```r
tibble(
  x = declared(c(1,2,"a", "b", "a", 1, 2, "b", "b"), na_values=c("a", "b")),
  y = 1:9,
) |>
  group_by(x) |>
  mutate(y_mean = mean(y), n = n())
#> # A tibble: 9 × 3
#> # Groups:   x [3]
#>   x             y y_mean
#>   <chr+lbl> <int>  <dbl>
#> 1     1         1    3.5
#> 2     2         2    4.5
#> 3 NA(a)         3    5.8
#> 4 NA(b)         4    5.8
#> 5 NA(a)         5    5.8
#> 6     1         6    3.5
#> 7     2         7    4.5
#> 8 NA(b)         8    5.8
#> 9 NA(b)         9    5.8
```

(All rows with declared na labels are getting the mean of the entire group of declared `NA` values, not just for that particular label)

**Comment by dusadrian** [comment]
Yes and again, any solution to this behavior needs to be implemented in tidyverse, for long term consistency.
I agree that tidyverse is here to stay, although I have my own opinion about it. Personally, I don't use it and don't even feel the need to use it (perfectly fine with base R).
Just look at this:
```r
dfm <- tibble(
  x = declared(c(1,2,"a", "b", "a", 1, 2, "b", "b"), na_values=c("a", "b")),
  y = 1:9,
)

library(admisc)
using(undeclare(dfm, drop = TRUE), mean(y), split.by = x)

  mean
1  3.5
2  4.5
a  4.0
b  7.0
```
To me, this is even more intuitive than those dplyr syntaxes. I could tweak the function `using()` to better cater the declared objects so the data frame will not need to be undeclared first. The syntax could then be even more simple such as:
`using(dfm, mean(y), split.by = x)`

(and this, I believe, cannot be beaten in simplicity)
