### ISSUE TITLE
Pillar column displays incorrect type

### ISSUE THREAD

**Issue by khusmann** [dusadrian/declared#8]
Just a little thing -- looks like the pillar column displays incorrect type for numeric cols with char missing reasons:

```r
(x <- declared(c(1,2,"a", "b", "a", 1, 2, "b", "b"), na_values=c("a", "b")))
#> <declared<numeric>[9]>
#> [1]     1     2 NA(a) NA(b) NA(a)     1     2 NA(b) NA(b)
#> Missing values: a, b
```

x is correctly listed as `<declared<numeric>[9]>`, and also correctly shows it's a numeric type:

```r
is.numeric(x)
#> [1] TRUE
```

but then inside the tibble it displays `<chr+lbl>` for the pillar column label:

```r
tibble(x)
#> # A tibble: 9 × 1
#>   x        
#>   <chr+lbl>
#> 1     1    
#> 2     2    
#> 3 NA(a)    
#> 4 NA(b)    
#> 5 NA(a)    
#> 6     1    
#> 7     2    
#> 8 NA(b)    
#> 9 NA(b)
```

**Comment by dusadrian** [comment]
See the issue [https://github.com/dusadrian/declared/issues/7](https://github.com/dusadrian/declared/issues/7) for the explanation.
